### ISSUE TITLE
Conda installation error

### ISSUE THREAD

**Issue by acoat** [VACUMM/sonat#1]
when running: conda install -c vacumm -c conda-forge -c uvcdat  sonat
the answer is:

UnsatisfiableError: The following specifications were found to be incompatible with each other:
Package vacumm conflicts for:
sonat -> vacumm[version='>=3.3.0|>=3.4.0|>=3.4.1']
Package libsangoma_tools conflicts for:
sonat -> libsangoma_tools[version='>=2.0.1']
Package jinja2 conflicts for:
sonat -> jinja2
Package nose conflicts for:
sonat -> nose
Package libgcc conflicts for:
sonat -> libgcc[version='>=4.7|>=4.8.5']
Package uvcdat conflicts for:
sonat -> uvcdat[version='2.8.0|>=2.8.0']

**Comment by stefraynaud** [comment]
I built new conda packages for vacumm, sphinx-fortran and sonat.
The installation procedure is also updated:

     conda install -c vacumm -c conda-forge -c defaults sonat
